name: Literals
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
           
            - env:
                LITERAL_NULL: ${{ null }}
                LITERAL_BOOLEAN: ${{ true }}
                LITERAL_NUMBER: ${{ 124 }}
                LITERAL_STRING: ${{ 'Hello' }}
                LITERAL_OMIT_STRING: World
              run: printenv | grep 'LITERAL_'